# Generated by Django 6.1.1 on 2026-09-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0002_cliente_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='valor_custo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
