# Generated by Django 6.1.1 on 2026-09-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0002_cliente_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Enviado', 'Enviado'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado'), ('Finalizado', 'Finalizado')], default='Rascunho', max_length=20),
        ),
    ]
