# Generated by Django 6.1.1 on 2026-09-08 23:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0003_rename_preco_produto_valor_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='margem_lucro',
            field=models.DecimalField(choices=[(Decimal('1.30'), '30%'), (Decimal('1.35'), '35% (Padrão)'), (Decimal('1.40'), '40%'), (Decimal('1.50'), '50%'), (Decimal('2.00'), '100% (Dobro)')], decimal_places=2, default=Decimal('1.35'), max_digits=4),
        ),
    ]
