# Generated by Django 6.1.1 on 2026-09-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0004_produto_margem_lucro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentoitem',
            name='preco_unitario',
        ),
        migrations.AddField(
            model_name='orcamentoitem',
            name='preço_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
